<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'كود التحقق غير صحيح' => 'Wrong OTP',
    'لقد قمت بتقديم عرض على ذلك الطلب من قبل' => 'You submitted an offer on this request before',        
    'تم تعديل الطلب بنجاح' => 'Your request has been updated successffully',    
    'قمت بقبول عرض سابق' => 'You accepted one offer before' ,
    'الطلب غير موجود'=>'The request is not found',
    'البيانات غير صحيحه' => 'Invalid Data' ,
    'تم تغيير الموقع بنجاح' => 'Location changed successfully',
    'لم يتم الموافقه على الحساب بعد' => 'account not approved yet to be able use this feature',
    'تم رفع الملفات بنجاح' => 'Files uploaded successfully',
    'دخول غير مصرح به' => 'Invalid access',
    'لقد اضفت طلب سابق من قبل' => 'You added previous request before',
    'لا يمكن تعديل حاله الجلسة قبل موعدها' => 'Session can not start before its time',
    'تاريخ الجلسه لم يأتى بعد' => 'Session date is not correct' ,
    'تم الدفع بنجاح' => 'Payment has been completed successfully',
    'تم قبول العرض بنجاح' => 'Offer has been accepted successffully',
    'العرض غير موجود' => 'Offer not found',
    'لا يمكن ان تقوم بتقييم نفس الطلب مرتين' => 'You can\'t rate the same request two times',
    'لقد قمت بدفع فاتوره الطلب من قبل' => 'You paid this request before',
    'تم حذف الحساب البنكى بنجاح' => 'Bank account has been deleted successfully',
    'حدث خطا ما برجاء قم بفحص ذلك مجددا' => 'There is an error occured please check this again',
    'الحساب البنكى غير موجود' => 'The bank account data not found',
    'عملية السحب تمت بنجاح' => 'Withdrawal proccess has been successeded',    
    'المستخدم غير موجود' => 'User not found' ,
    'تم اضافة عنوان العميل بنجاح' => 'Customer location has been added successfully',
    'تم حذف العنوان بنجاح' => 'Location has been deleted successfully',
    'العنوان غير صحيح' => 'Location is invalid',
    'تم اضافة الاقارب بنجاح' => 'Relatives added successfully',
    'تم تغيير العنوان بنجاح' => 'Location changed successfully',
    'تم حذف المستخدم بنجاح' => 'User has been deleted successfully',
    'لا يمكن حذف الحساب. هناك جلسات قيد التنفيذ' => 'You can`t delete account.There are Sessions in progress',
    'المنطقة المحدده بعيده عن النانى . من المحتمل رفض الطلب' => 'The specified area is far from Nani, the request may be rejected.',
    'كود التحقق الخاص بك هو ' => 'Your otp code is ',
    'لم يتم ارسال كود التحقق بنجاح. برجاء المحاولة مره أخرى' => 'OTP didn`t send please try again',
    'تم تعديل اللغة بنجاح' => 'Locale changed successfully',
    'المستخدم غير موجود' => 'User not found.',
    'عفوا لا يمكنك الموافقه قبل انهاء الجلسه الحاليه' => 'Sorry, you cannot approve before ending the current session.',
    'السعر يجب ان يكون اكبر من ' => 'price must be larger than ',
    'تم تغيير حالة الطلب بنجاح' => 'Request has been updated successfully',
    'النانى غير موجوده' => 'Nany Not Found',
    'ليس لديك صلاحية' => 'You don not have access',

];
