<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    //Menu
    'Products' => 'المنتجات',
    'About US' => 'نبذة عنا',
    'Dry Website' => 'زور دراى',

    'IMPORTANT LINKS' => 'روابط تهمك',
    'ABOUT' => 'نبذة عنا',
    'Home' => 'الرئيسية',
    'Contact US' => 'اتصل بنا',
    //Home Page
    'VISSION' => 'الرؤية',

    'MISSION' => 'المهمة',
    'OBJECTIVES' => 'الهدف',

    'Read More' => 'عرض المزيد',
    'Pieces' => 'قطع',
    'Size' => 'المقاس',
    'Top Sheet' => 'الورقة العلوية',
    'Style' => 'الطراز',
    'View All' => 'عرض الكل',
    'Join us as B2B' => 'انضم إلينا كـ B2B',
    'You can join us from anywhere' => 'يمكنك الانضمام إلينا من أي مكان',
    'Are you importer or need to be agent' => 'هل أنت مستورد أو تحتاج إلى أن تكون وكيلاً',
    'in your country' => 'في بلدك',
    "Let's join" => 'إنضم إلينا',
    'Egypt' => 'مصر',
    'are you a pharmacy' => 'هل انت صيدلية',
    'Pharmacies' => 'صيدليات',
    'More than' => 'أكثر من',
    'Companies' => 'شركات',
    'pharmacies and more than 200 companies' => 'صيدليات وأكثر من 200 شركة',
    'Our products are available in more than 2000' => 'منتجاتنا متوفرة في أكثر من 2000',
    'Expanding faster' => 'التوسع بشكل أسرع',
    'and understood our Privacy Policy' => 'وفهمت سياسة الخصوصية الخاصة بنا',
    'Submit' => 'إرسال',
    'By clicking the button below you agree to our terms of Service and have read' => 'بالنقر فوق الزر أدناه ، فإنك توافق على شروط الخدمة الخاصة بنا وقد قرأت ',
    'Your details' => 'بياناتك',
    'What option you are interested in?' => 'ما هو الخيار الذي تهتم به؟',
    'Leave your details and we will contact you' => 'اترك بياناتك وسنتصل بك',
    "Let's get in touch" => 'تواصل معنا',
    'frontend', 'All Rights Reserved, Cosmocare.com' => 'جميع الحقوق محفوظة لشركة Cosmocare.com',
    //contact form validate
    'Please Enter your name' => 'من فضلك ادخل الاسم',
    'Please Enter your phone' => 'من فضلك ادخل الجــوال',
    'Please Enter your email' => 'من فضلك ادخل الايميل',
    'Please Enter your message' => 'من فضلك اذكر الرسالة أو الشكوى',

    'Please Enter your company' => 'من فضلك ادخل شركتك',
    'Please Enter valid code' => 'فضلا ادخل الكود بشكل صحيح',
    'Please Enter valid email' => 'فضلا ادخل ايميل صحيح',
    'Please choose your preferred option' => 'من فضلك اختر الخيار المفضل للتواصل',
    'Please Enter a valid phone' => 'فضلا ادخل هاتف صحيح',
    'Full name*' => 'اسمك *',
    'E-Mail address*' => 'البريد الالكترونى *',
    'Company' => 'شركتك',
    'Additional info' => 'نص الرساله او الشكوى',
    'Verification Code' => 'كود التحقق',
    //Products Page
    'Get to know our products' => 'تعرف على منتجاتنا',
    'All' => 'كل المنتجات',
    'New' => 'جديد',
    'Definition' => 'وصف المنتج',
    'More Details' => 'المزيد عن المنتج',
    '1 piece' => 'قطعه واحده',
    //Footer
    'COSMOCARE' => 'كوزموكير',
    'Dry Social Media' => 'تابع دراى',
    'Dry Facebook' => 'على الفيسبوك',
    'Dry Instagram' => 'على الأنستاجرام',
    'Dry Tiktok' => 'على التيكتوك',
    'Dry Youtube' => 'على اليوتيوب',
    //home page
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'شكرا لتواصلك معنا سيتم الاتصال بك فى اقرب وقت',
    'VISION' => 'الرؤية',
    'Countries' => 'الدول',
    'Points of sales' => 'نقاط البيع',
    'Available in' => 'متاح في',
    //B2B
    'Kindly fill this data to start Communicating.' => 'قم بإكمال البيانات التالية لنتصل بك',
    'Last name*' => 'الاسم الأخير*',
    'Country*' => 'الدولة*',
    'Field*' => 'المجال*',
    'Position*' => 'الموقع*',
    'Experience Years*' => 'سنين الخبرة*',
    'Other Details*' => 'بيانات أخرى*',

    'From Egypt' => 'من مصر',
    'Other Country' => 'دولة أخرى',

    //B2B
    'Please Enter your Company' => 'من فضلك ادخل اسم شركتك',
    'Please Enter your Field' => 'من فضلك ادخل مجال العمل',
    'Please Enter your Position' => 'من فضلك ادخل وظيفتك',

    'Please Enter your Experience' => 'من فضلك ادخل سنين الخبره', '' => '',
    //About Page
    'About Cosmocare' => 'نبذة عن Cosmocare',
    //General Messages
    'Terms and Conditions' => 'الشروط والاحكام',
    'Send' => 'ارسل',
    'Contact Info' => 'معلومات التواصل',
    'Address' => 'العنوان',
    'Phone' => 'التليفون',
    'Email' => 'البريدالالكتروني',
    'Name' => 'الاسم',
    'Mobile' => 'رقم الجوال',
    'Message' => 'الرسالة',
    'Your Message has been sent.' => 'تم ارسال رسالتك بنجاح',
    'Please check your entered Data.' => 'فضلا تاكد من البيانات المدخلة',
    "Please prove that you are a real person" => " أنا لست برنامج روبوت",
    "You added previous request before" => " لقد أضفت الطلب السابق من قبل",
    "Your request has been updated successffully" => "تم تحديث طلبك بنجاح",
    "Session date is not correct" => "تاريخ الجلسة غير صحيح",
    "The request is not found" => "لم يتم العثور على الطلب",
    "Session can not start before its time" => "لا يمكن أن تبدأ الجلسة قبل موعدها",
    'You submitted an offer on this request before' => 'لقد قمت بتقديم عرض على ذلك الطلب من قبل',
    'Wrong OTP' => 'كود التحقق غير صحيح',
    'You accepted one offer before' => 'قمت بقبول عرض سابق',
    'Invalid Data' => 'البيانات غير صحيحه',
    'account not approved yet to be able use this feature' => 'لم يتم الموافقه على الحساب بعد',
    'Files uploaded successfully' => 'تم رفع الملفات بنجاح',
    'Invalid access' => 'دخول غير مصرح به',
    'Payment has been completed successfully' => 'تم الدفع بنجاح',
    'Offer has been accepted successffully' => 'تم قبول العرض بنجاح',
    'Offer not found' => 'العرض غير موجود',
    'You can\'t rate the same request two times' => 'لا يمكن ان تقوم بتقييم نفس الطلب مرتين',
    'You paid this request before' => 'لقد قمت بدفع فاتوره الطلب من قبل',
    'Bank account has been deleted successfully' => 'تم حذف الحساب البنكى بنجاح',
    'There is an error occured please check this again' => 'حدث خطا ما برجاء قم بفحص ذلك مجددا',
    'The bank account data not found' => 'الحساب البنكى غير موجود',
    'Withdrawal proccess has been successeded' => 'عملية السحب تمت بنجاح',
    'User not found' => 'المستخدم غير موجود',
    'Customer location has been added successfully' => 'تم اضافة عنوان العميل بنجاح',
    'Location has been deleted successfully' => 'تم حذف العنوان بنجاح',
    'Location is invalid' => 'العنوان غير صحيح',
    'Relatives added successfully' => 'تم اضافة الاقارب بنجاح',
    'Location changed successfully' => 'تم تغيير العنوان بنجاح',
    'User has been deleted successfully' => 'تم حذف المستخدم بنجاح',
    'You can`t delete account.There are Sessions in progress' => 'لا يمكن حذف الحساب. هناك جلسات قيد التنفيذ',
    'The specified area is far from Nani,ب the request may be rejected.' => 'المنطقة المحدده بعيده عن النانى . من المحتمل رفض الطلب',
    'Your otp code is ' => 'كود التحقق الخاص بك هو ',
    'OTP didn`t send please try again' => 'لم يتم ارسال كود التحقق بنجاح. برجاء المحاولة مره أخرى',
    'Locale changed successfully' => 'تم تعديل اللغة بنجاح',
    'User not found.' => 'المستخدم غير موجود',
    'Sorry, you cannot approve before ending the current session.' => 'عفوا لا يمكنك الموافقه قبل انهاء الجلسه الحاليه',
    'price must be larger than ' => 'السعر يجب ان يكون اكبر من ',
    'Request has been updated successfully' => 'تم تغيير حالة الطلب بنجاح',
    'Nany Not Found' => 'النانى غير موجوده',
    'You don not have access' => 'ليس لديك صلاحية',
    'Don`t have an account?' => 'ليس لديك حساب؟',
    'Identity' => 'الهوية',
    'Have an account?' => 'هل لديك حساب؟',
    'Login' => 'تسجيل الدخول',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
];
