<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => 'جديد',
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Active' => 'فعال',
    'Add new' => 'أضف جديد',
    'Add new root' => 'اضف عنصر رئيسى',
    'Admin Settings' => 'اعدادات الادمن',
    'Already at bottom-most {node} in the hierarchy.' => '',
    'Already at left-most {node} in the hierarchy.' => '',
    'Already at right-most {node} in the hierarchy.' => '',
    'Already at top-most {node} in the hierarchy.' => '',
    'Are you sure you want to remove this {node}?' => 'هل انت متاكد من حذف {node}?',
    'Cannot create {node}. Parent node is not saved or is invalid.' => 'لا يمكن اضافه {node}.',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => 'لا يمكن تحريك {nodes}',
    'Cannot move this {node} as the {node} details are not saved yet.' => 'لا يمكن تحريك {nodes} البيانات غير مكتمله',
    'Child Allowed' => 'مسموح باضافه ابن',
    'Clear search results' => 'امسح نتائج البحث',
    'Collapsed' => 'مغلقه',
    'Default' => 'الافتراضى',
    'Delete' => 'حذف',
    'Depth' => 'المستوى',
    'Disabled' => 'غير فعال',
    'Error removing the {node}. Please try again later.' => 'خطأ اثناء حذف ال {node}.  يرجى المحاوله مره اخرى',
    'Error while creating the {node}. Please try again later.' => 'خطأ اثناء حفظ ال {node}. يرجى المحاوله مره اخرى',
    'Error while moving the {node}. Please try again later.' => '',
    'Error while removing the {node}. Please try again later.' => '',
    'Error while saving the {node}. Please try again later.' => '',
    'Error while viewing the {node}. Please try again later.' => '',
    'ID' => 'رقم',
    'Icon' => 'ايقونه',
    'Icon Type' => 'نوع الايقون',
    'Left' => 'يسار',
    'Movable Down' => 'حرك لاسفل',
    'Movable Left' => 'حرك لليسار',
    'Movable Right' => 'حرك لليمين',
    'Movable Up' => 'حرك للاعلى',
    'Move Down' => 'حرك للاسفل',
    'Move Left' => 'حرك لليسار',
    'Move Right' => 'حرك لليمين',
    'Move Up' => 'حرك لاعلى',
    'Name' => 'الاسم',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => '',
    'Read Only' => 'قراءه فقط',
    'Refresh' => 'تحديث',
    'Removable' => 'قابل للحذف',
    'Removable (with children)' => '',
    'Reset' => 'Reset',
    'Right' => '',
    'Root' => 'القائمة',
    'Save' => 'حفظ',
    'Saved the {node} details successfully.' => 'تم حفظ تفاصيل ال {node} بنجاح',
    'Search...' => 'بحث ...',
    'Select a {node} by clicking on one of the tree items.' => 'اختار {node}  بالضغط عليها',
    'Select...' => 'اختار ... ',
    'Selected' => 'تم الاختيار',
    'The selected {node} cannot be moved.' => 'لا يمكن حذف ال {node}',
    'The untitled {node} was removed.' => 'تم حذف {node} ',
    'The {node} was moved successfully.' => 'تم تحريك {node}  بنجاح',
    'The {node} was removed successfully.' => 'تم حذف {node} بنجاح',
    'The {node} was successfully created.' => 'تم انشاء {node} بنجاح',
    'This operation is not allowed.' => 'هذه العمليه غير مسموح بها',
    'Untitled' => 'بدون عنوان',
    'Visible' => 'مرئى',
    'You cannot add children under this {node}.' => 'لا يمكن اضافه ابناء تحت {node}',
    'node' => 'عنصر',
    'nodes' => 'عناصر',
    '{node} # {id} - \'{name}\': {error}' => '',
];
